### ISSUE TITLE
Milestone and Component UI Mockups

### ISSUE THREAD

**Issue by RichardLitt** [BeagleLab/voyage#43]
This is a list of components, sections (in the sidebar), and modals, used in the Milestone and Component Mockups hosted on the local server. 
### Milestones:
- [x] M1: Plugin Open
- [x] M2: Hidden
- [x] M3: Author Profile
- [x] M4: Publication Graph
- [x] M5: Tags
- [x] M6: BibTeX
- [x] M7: Annotations
- [ ] M8: User Groups
### Components:
- [x] Notifications
- [x] Save
- [x] Publication List
- [x] Publication List Wrapper
- [x] Tags List
- [x] Tags List Wrapper
- [ ] Social Sharing Component - Facebook, Twitter - Panel
- [x] Author Contact Information Links Component
- [ ] Search within Citations / Refs
- [ ] Copy Citation in Citation Graph
- [x] Journal Link out to PLOS website, etc. 
### Sections:
- [x] Notification in sidebar
- [x] Save 
- [x] Publication Metadata
- [x] Graph
- [x] AltGraph
- [x] Tags
- [x] Champion
- [x] Annotation Counts
- [x] Cite box
- [x] TOC Section
- [ ] Collapsible Tags for sections (component?)
- [ ] Tag sidebar which floats along with the view, showing tags for each section
- [x] NCBO Tags
- [x] Supplementary research Section
- [x] Link out to Supplementary Research Section
- [x] Statistically Improbable Phrases section
- [x] Abstract Section
- [ ] Tag section for papers
- [x] Paper Panel (for papers not currently in the viewer)
- [x] Figs Section
- [x] User Sign In // Sign Up (w. component)
- [x] User Read Later (w. component)
- [ ] About Component (Sidebar Footer)
- [ ] User Groups (w. component)
- [x] Dat & Data (w. component)
### Modals:
- [x] Author
- [x] Cite & Referencing
- [x] Citation Graph
- [x] Tags
- [ ] Edit Metadata format Panel
- [x] Journal Panel
- [ ] Paper Citation Visualisations in Panel
- [ ] Annotation Minipanel with input box
- [ ] Reference Click and Panel
- [ ] Citation Graph Tree
- [ ] See Other Flagged Papers panel
- [ ] See Champion Panel
- [ ] See Nominate Panel
- [x] Tag Panel
- [ ] Email highlighted Text panel
- [ ] User Dashboard Panel
### Other
- [ ] PDFJS Viewer
- [ ] HTML Pages(? How do we deal with these?) Link to PDF from HTML pages
